heaps/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from heaps import settings

handler404 = 'heaps_app.views.handler404'

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'ckeditor', include('ckeditor_uploader.urls')),
    url(r'^heaps-stat/', include('heaps_stat.urls', namespace='heaps_stat')),
    url(r'', include('social.apps.django_app.urls', namespace='social')),
    url(r'^', include('heaps_app.urls', namespace='heaps_app')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

heaps_app/urls.py
from django.conf.urls import include, url
from heaps_app import views
from heaps_app import mail

account_patterns = [
    url(r'^login/$', views.account_login, name='account-login'),
    url(r'^registration/$', views.account_registration, name='account-registration'),
    url(r'^logout/$', views.account_logout, name='account-logout'),
    url(r'^my-subscribes/$', views.AccountMySubscribes.as_view(), name='account-my-subscribes'),
    url(r'^settings/$', views.AccountSettings.as_view(), name='account-settings'),
    url(r'^forgotten-password/$', views.account_forgotten_password, name='account-forgotten-password'),
    url(r'^add-person/$', views.AccountCelebrityAddView.as_view(), name='account-celebrity-add'),
]

person_patterns = [
    url(r'^email-sent/$', mail.email_validation),
    url(r'^(?P<slug>[\w-]+)/$', views.CelebrityView.as_view(), name='celebrity-view'),
    url(r'^(?P<slug>[\w-]+)/subscribe/$', views.celebrity_subscribe, name='celebrity-subscribe'),
    url(r'^(?P<slug>[\w-]+)/social-posts-loader/$', views.social_posts_loader, name='celebrity-social-posts-loader'),
    url(r'^(?P<slug>[\w-]+)/social-posts-actions/$', views.social_posts_actions, name='celebrity-social-posts-actions'),
]

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^search/$', views.SearchView.as_view(), name='search'),
    url(r'^person/', include(person_patterns)),
    url(r'^account/', include(account_patterns)),
]

heaps_app/views.py
import hashlib
import urllib
from requests import HTTPError
from urlparse import urlparse
from django.utils import timezone
from django.core.cache import cache
from django.views.generic import ListView, CreateView, DetailView, TemplateView
from django.http import JsonResponse, HttpResponseForbidden, HttpResponseNotFound
from django.shortcuts import redirect, render
from django.db.models import Q
from django.template.loader import get_template
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator
from heaps_app import models, forms, mail, social_workers
from django.utils.translation import ugettext, ugettext_lazy as _


class CelebritiesFilterMixin(object):
    def get_queryset(self):
        qs = super(CelebritiesFilterMixin, self).get_queryset()

        filter_tags = self.request.GET.getlist('filter_tag', None)

        if filter_tags:
            filter_career = models.Filter.objects.filter(pk__in=filter_tags, filter_type='career')
            filter_social_network = models.Filter.objects.filter(pk__in=filter_tags, filter_type='social_network')

            if filter_career:
                qs = qs.filter(filter__in=filter_career)

            if filter_social_network:
                qs = qs.filter(filter__in=filter_social_network)

            qs = qs.distinct()

        query = self.request.GET.get('query', None)

        if query:
            if query.strip():
                query = query.strip()
                qs = qs.filter(
                    Q(firstname__icontains=query) | Q(lastname__icontains=query) | Q(nickname__icontains=query)
                )
            else:
                qs = qs.none()

        return qs


class CelebritiesPaginatedAjaxMixin(object):
    celebrities_template = 'heaps_app/_celebrities_block.html'

    def get(self, request, *args, **kwargs):
        result = super(CelebritiesPaginatedAjaxMixin, self).get(request, *args, **kwargs)

        if request.is_ajax():
            celebrities_template = get_template(self.celebrities_template)

            return JsonResponse({
                'celebrities': celebrities_template.render({
                    'celebrities': result.context_data['celebrities'],
                    'request': request,
                }),
                'paginate_has_next': result.context_data['page_obj'].has_next(),
            })
        return result


class FormResponseMixin(object):
    def form_valid(self, form):
        response = super(FormResponseMixin, self).form_valid(form)

        if self.request.is_ajax():
            return JsonResponse({
                'success': True,
                'message': self.success_message
            })
        else:
            return response

    def form_invalid(self, form):
        response = super(FormResponseMixin, self).form_invalid(form)

        if self.request.is_ajax():
            return JsonResponse({
                'errors': form.errors
            })
        else:
            return response


class IndexView(CelebritiesPaginatedAjaxMixin, ListView):
    template_name = 'heaps_app/index.html'
    queryset = models.Celebrity.public_records.get_queryset()
    context_object_name = 'celebrities'
    paginate_by = 6

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)

        if 'partial_pipeline' in self.request.session:
            context['backend'] = self.request.session['partial_pipeline']['backend']
            context['email_verification_form'] = forms.EmailVerificationForm()

        email_validation_address = self.request.session.get('email_validation_address')

        if 'validation_sent' in self.request.GET and email_validation_address:
            context['message'] = _(
                'An email validation was sent to {0}. Click the link sent to finish the authentication process.'
            ).format(email_validation_address)
            context['email_url'] = '//{0}'.format(email_validation_address.split('@')[1])

        return context


class SearchView(CelebritiesFilterMixin, CelebritiesPaginatedAjaxMixin, ListView):
    template_name = 'heaps_app/index.html'
    queryset = models.Celebrity.public_records.get_queryset()
    context_object_name = 'celebrities'
    paginate_by = 6


class CelebrityView(CelebritiesPaginatedAjaxMixin, DetailView):
    template_name = 'heaps_app/celebrity_view.html'
    context_object_name = 'celebrity'
    queryset = models.Celebrity.public_records.get_queryset()

    def get_context_data(self, **kwargs):
        context = super(CelebrityView, self).get_context_data(**kwargs)

        # Update object stat
        self.object.update_stat(self.request)

        related_celebrities = models.Celebrity.public_records.filter(
            filter__pk__in=self.object.filter.all(),
            filter__filter_type='career').distinct().exclude(pk=self.object.pk)

        paginator = Paginator(related_celebrities, 6)
        page_obj = paginator.page(self.request.GET.get('page', 1))

        context['celebrities'] = page_obj.object_list
        context['page_obj'] = page_obj

        return context


class AccountCelebrityAddView(FormResponseMixin, CreateView):
    template_name = 'heaps_app/account_celebrity_add.html'
    form_class = forms.CelebrityAddForm
    success_message = ugettext('Celebrity record add.')

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(AccountCelebrityAddView, self).dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('heaps_app:account-celebrity-add')


class AccountMySubscribes(CelebritiesPaginatedAjaxMixin, ListView):
    template_name = 'heaps_app/account_my_subscribes.html'
    model = models.Celebrity
    context_object_name = 'celebrities'
    paginate_by = 6

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(AccountMySubscribes, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        return models.Celebrity.public_records.filter(pk__in=self.request.user.celebrity_subscribe.all())


class AccountSettings(TemplateView):
    template_name = 'heaps_app/account_settings.html'
    account_settings_info_form = forms.AccountSettingsInfoForm
    account_settings_avatar_form = forms.AccountSettingsAvatarForm

    success_message = ugettext('Account settings updated')
    change_email_message = ugettext(
        'An email validation was sent to {0}. Click the link sent to finish the authentication process.')
    ajax_response_data = {}

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(AccountSettings, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(AccountSettings, self).get_context_data(**kwargs)

        # Set initial data
        context['settings_info_form'] = self.account_settings_info_form(initial={
            'first_name': self.request.user.first_name,
            'last_name': self.request.user.last_name,
            'email': self.request.user.email,
        })

        context['settings_avatar_form'] = self.account_settings_avatar_form()

        return context

    def get(self, request, *args, **kwargs):
        # Email actions link handler
        action = request.GET.get('action')
        action_hash = request.GET.get('action_hash')

        if action and action_hash:
            action_info = action in request.session and request.session.pop(action)

            if action_info and action_info.pop('action_hash') == action_hash:
                return getattr(self, '_' + action)(**action_info)

        return super(AccountSettings, self).get(request, args, kwargs)

    def post(self, request, *args, **kwargs):
        form_class = request.POST.get('form_type')
        relogin = False

        if not form_class or not hasattr(self, form_class):
            return HttpResponseForbidden("Access denied")

        form = getattr(self, form_class)(request.POST, request.FILES)

        if form.is_valid():
            user = models.User.objects.get(pk=request.user.pk)

            password = 'password' in form.cleaned_data and form.cleaned_data.pop('password')
            password_repeat = 'password_repeat' in form.cleaned_data and form.cleaned_data.pop('password_repeat')
            email = 'email' in form.cleaned_data and form.cleaned_data.pop('email')

            # Check user change password
            if password and password_repeat:
                user.set_password(password)
                relogin = True

            # Save user model attributes
            for attr, value in form.cleaned_data.iteritems():
                if hasattr(user, attr):
                    setattr(user, attr, value)

            user.save()

            if relogin:
                user_credentials = authenticate(email=user.email, password=password)

                login(request, user_credentials)

            # Check user change email
            if email and email != user.email:
                action_hash = hashlib.sha1(str(user.pk) + str(timezone.now())).hexdigest()
                change_email_url = reverse('heaps_app:account-settings') + '?' + urllib.urlencode({
                    'action': 'account_change_email',
                    'action_hash': action_hash,
                })

                change_email_url = self.request.build_absolute_uri(change_email_url)

                self.request.session['account_change_email'] = {
                    'new_email': email,
                    'action_hash': action_hash
                }

                mail.account_change_email_notification(email, change_email_url)

                self.ajax_response_data = {

heaps_app/templates/heaps_app/account_my_subscribes.html
{% extends 'heaps_app/base_html.html' %}

{% block title %}Мои подписки{% endblock %}

{% block content %}
    {% if celebrities %}
        {% include 'heaps_app/_celebrities_block.html' %}
    {% else %}
        <div class="col-md-10 wrap-info-message">
            <div class="info-message">
                Вы еще ни на кого не подписаны.
                Подпишитесь на знаменитость из общего списка, и глобальная социальная сеть HeapsMe,
                в будущем, будет собирать для вас самые последние новости знаменитостей из всех социальных сетей мира.
            </div>
        </div>
    {% endif %}
{% endblock %}

heaps_app/templates/heaps_app/base_html.html
{% load static %}
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>{% block title %}Heaps.me{% endblock %}</title>
    <link href="{% static 'heaps_app/favicon.ico' %}" rel="shortcut icon" type="image/x-icon" />
    {% block seo %}{% endblock %}
    <!--[if lte IE 8]><script src="{% static 'heaps_app/js/ie/html5shiv.js' %}<![endif]-->
    <link rel="stylesheet" href="{% static 'heaps_app/js/bxslider/css/jquery.bxslider.css' %}">
    <link rel="stylesheet" href="{% static 'heaps_app/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'heaps_app/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'heaps_app/css/style.css' %}">
    <!--[if lte IE 8]><link rel="stylesheet" href="{% static 'heaps_app/css/ie8.css' %}"><![endif]-->
    <!--[if lte IE 9]><link rel="stylesheet" href="{% static 'heaps_app/css/ie9.css' %}"><![endif]-->
    {% block additional_style %}{% endblock %}
</head>
<body>
<div id="header">
    <div id="sidebarToggle"><a href="#sidebar" class="toggle"></a></div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8">
                <form action="{% url 'heaps_app:search' %}" class="form-search" method="get">
                    <div class="search-wrap">
                        {{ search_form.query }}
                        <div class="but-filter"><i class="fa fa-caret-down"></i><span>Фильтр</span></div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% if user.is_authenticated %}
    {% include 'heaps_app/sidebar_user.html' %}
{% else %}
    {% include 'heaps_app/sidebar_guest.html' %}
{% endif %}

<div id="main">
    <div id="main-wrapper">
        {% if filter_tags_career or filter_tags_social_networks %}
            <form id="filter-form" action="{% url 'heaps_app:search' %}" class="form-filter-gen">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="filter-gen-wrapper">
                                <span>Фильтр</span>
                                {% if filter_tags_career %}
                                    <div class="filter-wrap-category clearfix">
                                        <ul>
                                            {% for item in filter_tags_career %}
                                                <li class="{{ item.css_class }} {% if item in current_tags %}active{% endif %}">
                                                    <label>
                                                        <span class="descr-link-ic">{{ item.title }}</span>
                                                        {% if item in current_tags %}
                                                            <input id="filter-tag-{{ item.id }}" type="checkbox"
                                                                   name="filter_tags" value="{{ item.id }}"
                                                                   checked="checked">
                                                        {% else %}
                                                            <input id="filter-tag-{{ item.id }}" type="checkbox"
                                                                   name="filter_tags" value="{{ item.id }}">
                                                        {% endif %}
                                                    </label>
                                                </li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                {% endif %}
                                {% if filter_tags_social_network %}
                                    <div class="filter-wrap-social clearfix">
                                        <ul class="sl-soc-filter-gen">
                                            {% for item in filter_tags_social_network %}
                                                <li class="{{ item.css_class }} {% if item in current_tags %}active{% endif %}">
                                                    <label>
                                                        {% if item in current_tags %}
                                                            <input id="filter-tag-{{ item.id }}" type="checkbox"
                                                                   name="filter_tags" value="{{ item.id }}"
                                                                   checked="checked">
                                                        {% else %}
                                                            <input id="filter-tag-{{ item.id }}" type="checkbox"
                                                                   name="filter_tags" value="{{ item.id }}">
                                                        {% endif %}
                                                    </label>
                                                </li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                {% endif %}
                                <div class="buttons-filter-wrapper clearfix">
                                    <button type="submit">Применить</button>
                                    <button type="reset">Сбросить фильтр</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        {% endif %}
        <div class="section-content">
            <div class="container-fluid">
                <div class="row">
                    {% if current_tags %}
                        <div class="col-md-12">
                            <div class="filter-indicators-wrapper clearfix">
                                <ul class="clearfix">
                                    <li>Фильтруется:</li>
                                    {% for item in current_tags %}
                                        <li class="{{ item.css_class }}">
                                            <a href="#" data-store-id="{{ item.id }}">{{ item }}</a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    {% endif %}

                    {% block content %}{% endblock %}
                </div>
            </div>
        </div>
        <footer>
            <div class="container-fluid">
                <div class="row ">
                    <div class="col-md-12">
                        <ul>
                            <li><a href="https://vk.com/board79890758">Вопрос-Ответ</a></li>
                            <li><a href="https://vk.com/heapsme">Официальное сообщество vk</a></li>
                            <li>© {% now 'Y' %} HeapsMe</li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        <div class="up-button">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-8">
                        <i class="fa fa-caret-up fa-lg"><span>Наверх</span></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="{% static 'heaps_app/js/jquery.min.js' %}"></script>
<script src="{% static 'heaps_app/js/bootstrap.js' %}"></script>
<script src="{% static 'heaps_app/js/bxslider/js/jquery.bxslider.min.js' %}"></script>
<script src="{% static 'heaps_app/js/url.min.js' %}"></script>
<!--[if lte IE 8]><script src="{% static 'heaps_app/js/ie/respond.min.js' %}"></script><![endif]-->
{% block additional_scripts %}{% endblock %}
<script src="{% static 'heaps_app/js/main.js' %}"></script>
<script src="{% static 'heaps_stat/js/stat.js' %}"></script>
<!-- Yandex.Metrika counter -->
<script type="text/javascript">
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter34181180 = new Ya.Metrika({
                    id:34181180,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true,
                    webvisor:true,
                    trackHash:true
                });
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
            f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = "https://mc.yandex.ru/metrika/watch.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/34181180" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->
</body>
</html>

heaps_app/templates/heaps_app/sidebar_guest.html
<div id="sidebar">
    <div class="start-content-sdb">
        <div id="logo"><a href="{% url 'heaps_app:index' %}">HeapsMe</a></div>
        <span class="subtitle-sdb">Знаменитости в соц сетях</span>
        <span class="subtitle-sdb-2">Узнавай первым<br> самые свежие<br> новости звезд</span>
        <span class="subtitle-sdb-3">Подписывайся<br> Следи за новостями<br> Авторизуйся<br> Добавь звезду</span>
        <span class="subtitle-sdb-4">Регистрируйся<br> прямо сейчас<br> и начни свой путь<br> в мир популярных<br> людей</span>

        <div class="but-log-reg-sdb">
            <button data-toggle="modal" data-target="#login" class="but-start-sdb">Вход</button>
            <button data-toggle="modal" data-target="#registration" class="but-start-sdb">Регистрация</button>
        </div>
    </div>
</div>

<div id="login" class="modal fade log-in-pop-up" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content clearfix">
            <form class="clearfix" action="{% url 'heaps_app:account-login' %}" method="post">
                {% csrf_token %}
                <div class="head-form">
                    <span>Вход на сайт</span>

                    <div class="but-close-form" data-dismiss="modal"></div>
                </div>
                {% for field in login_form %}
                    <div class="input-box">
                        <label for="{{ field.id_for_label }}"
                               class="ic-input {% cycle 'ic-log' 'ic-parol' %}"></label>
                        {{ field }}
                    </div>
                    <div class="unrer-dec"></div>
                {% endfor %}
                <button class="send">ВОЙТИ</button>
                <div class="social-form-box">
                    <div class="title-social-log-in">Или войти через:</div>
                    <ul class="social-log-in clearfix">
                        <li><a href="{% url 'social:begin' 'vk-oauth2' %}"></a></li>
                        <li><a href="{% url 'social:begin' 'twitter' %}"></a></li>
                        <li><a href="{% url 'social:begin' 'facebook' %}"></a></li>
                        <li><a href="{% url 'social:begin' 'google-plus' %}" id="google-plus-button"></a></li>
                    </ul>
                </div>
                <a class="link-forgot-log" href="#" data-toggle="modal" data-target="#forgotten-password">Напомнить
                    пароль</a>
                <a class="link-reg-log-mod" href="#" data-toggle="modal" data-target="#registration">Регистрация</a>
            </form>
        </div>
    </div>
</div>

<div id="registration" class="modal fade sign-up-pop-up" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content clearfix">
            <form action="{% url 'heaps_app:account-registration' %}" method="post">
                {% csrf_token %}
                <div class="head-form">
                    <span>Регистрация</span>

                    <div class="but-close-form" data-dismiss="modal"></div>
                </div>
                {% for field in registration_form %}
                    <div class="input-box">
                        <label for="{{ field.id_for_label }}"
                               class="ic-input {% cycle 'ic-log' 'ic-parol' 'ic-parol' %}"></label>
                        {{ field }}
                    </div>
                    <div class="unrer-dec"></div>
                {% endfor %}
                <button class="send">ОТПРАВИТЬ</button>
            </form>
        </div>
    </div>
</div>

<div id="forgotten-password" class="modal fade input-mail-pop-up" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content clearfix">
            <form action="{% url 'heaps_app:account-forgotten-password' %}" method="post">
                {% csrf_token %}
                <div class="head-form">
                    <span>Укажите ваш email:</span>
                </div>
                {% for field in password_forgotten_form %}
                    <div class="input-box">
                        <label for="{{ field.id_for_label }}" class="ic-input ic-log"></label>
                        {{ field }}
                    </div>
                    <div class="unrer-dec"></div>
                {% endfor %}
                <button class="send">ОТПРАВИТЬ</button>
            </form>
        </div>
    </div>
</div>

{% if backend %}
    <div id="email-verification" class="modal fade input-mail-pop-up" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content clearfix">
                <form action="{% url "social:complete" backend %}" method="post">
                    {% csrf_token %}
                    <div class="head-form">
                        <span>Введите почту всего один раз для подтверждения входа.</span>
                    </div>
                    {% for field in email_verification_form %}
                        <div class="input-box">
                            <label for="{{ field.id_for_label }}" class="ic-input ic-log"></label>
                            {{ field }}
                        </div>
                        <div class="unrer-dec"></div>
                    {% endfor %}
                    <button type="submit" class="send">ОТПРАВИТЬ</button>
                </form>
            </div>
        </div>
    </div>
{% endif %}

<div id="message-modal" class="modal fade go-mail-pop-up" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content clearfix">
            <div class="mod-go-mail">
                <div class="wrapper clearfix">
                    <div class="img-inf-mail"></div>
                    <div class="go-mail-info">
                        <span>{{ message }}</span>
                        <button class="but-go-mail clearfix" data-url="{{ email_url }}">Перейти на почту</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://apis.google.com/js/api:client.js"></script>

<script type="text/javascript">
    gapi.load('auth2', function () {
        var auth2;

        auth2 = gapi.auth2.init({
            client_id: "{{ google_plus_key }}",
            scope: "{{ google_plus_scope }}"
        });

        auth2.then(function () {
            var button = document.getElementById("google-plus-button");

            auth2.attachClickHandler(button, {}, function (googleUser) {

                var authResponse = googleUser.getAuthResponse();
                var $form;
                var $input;

                $form = $("<form>");
                $form.attr("action", "/complete/google-plus/");
                $form.attr("method", "post");
                $input = $("<input>");
                $input.attr("name", "access_token");
                $input.attr("value", authResponse.access_token);
                $form.append($input);
                // Add csrf-token if needed
                $(document.body).append($form);
                $form.submit();
            });
        });
    });
</script>

heaps_app/templates/heaps_app/sidebar_user.html
<div id="sidebar">
    <div class="user-descrpt-sidebar clearfix">
        <div id="logo"><a href="{% url 'heaps_app:index' %}">HeapsMe</a></div>
        <div class="descr-user-photo">
            <img src="{{ user.avatar.url }}" alt="{{ user }}" title="{{ user }}">
        </div>
        <span>{{ user.get_full_name }}</span>
    </div>

    <nav id="nav">
        <ul>
            <li>
                {% url 'heaps_app:index' as index_page %}
                <a href="{{ index_page }}" class="{% if index_page == request.path %}active{% endif %}">
                    <span class="icon fa-users">Все</span>
                </a>
            </li>
            <li>
                {% url 'heaps_app:account-my-subscribes' as account_my_subscribes_page %}
                <a href="{{ account_my_subscribes_page }}" class="{% if account_my_subscribes_page == request.path %}active{% endif %}">
                    <span class="icon fa-check-square-o">Мои подписки</span>
                </a>
            </li>
            <li>
                {% url 'heaps_app:account-celebrity-add' as account_celebrity_add_page %}
                <a href="{{ account_celebrity_add_page }}" class="{% if account_celebrity_add_page == request.path %}active{% endif %}">
                    <span class="icon fa-plus">Добавить</span>
                </a>
            </li>
            <li>
                {% url 'heaps_app:account-settings' as account_settings_page %}
                <a href="{{ account_settings_page }}" class="{% if account_settings_page == request.path %}active{% endif %}">
                    <span class="icon fa-cog">Настройки</span>
                </a>
            </li>
            <li>
                <a href="{% url 'heaps_app:account-logout' %}">
                    <span class="icon fa-power-off">Выход</span>
                </a>
            </li>
        </ul>
    </nav>
</div>

<div id="message-modal" class="modal fade go-mail-pop-up" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content clearfix">
            <div class="mod-go-mail">
                <div class="wrapper clearfix">
                    <div class="img-inf-mail"></div>
                    <div class="go-mail-info">
                        <span></span>
                        <button class="but-go-mail clearfix" data-url="">Перейти на почту</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>